version: "3"
services:
  nginx:
    ports: 
      - "3000:80"

  dockerop:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=eluo28
      - MONGO_PASSWORD=test
      - SESSION_SECRET=secret
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=eluo28
      - MONGO_INITDB_ROOT_PASSWORD=test
